import assert from 'node:assert/strict';
import test from 'node:test';
import { DEFAULT_SETTINGS, getAllPositions } from './constants';
import { autoFixViolations, autoGenerateDefense, validateAll } from './utils';
import type { DefenseAssignments, Player, Settings } from './types';

const roster = (count: number): Player[] => Array.from({ length: count }, (_, i) => ({
  id: String(i), name: i === 0 ? 'December' : `Player ${i}`, color: '#000000', active: true
}));
const relaxed: Settings = {
  ...DEFAULT_SETTINGS, requireDugout: false, requireEarlyInfieldByInning3: false,
  preventDuplicatePositionInGame: false, allowSamePositionBackToBack: true,
  maxConsecutiveInfield: 20, maxConsecutiveOutfield: 20, maxConsecutiveBench: 20
};
const repeated = (players: Player[], innings = 3): DefenseAssignments => ({
  innings, byInning: Object.fromEntries(Array.from({ length: innings }, (_, i) => [i + 1, {
    ...Object.fromEntries(getAllPositions().map((pos, j) => [pos, players[j]?.id])),
    dugout: players.slice(10).map(player => player.id)
  }]))
});

test('position repeat and back-to-back toggles are independent', () => {
  const players = roster(11);
  const assignments = repeated(players);
  assert.equal(validateAll(assignments, players, relaxed).errors.length, 0);
  assert(validateAll(assignments, players, { ...relaxed, preventDuplicatePositionInGame: true }).errors.some(e => e.includes('times in this game')));
  assert(validateAll(assignments, players, { ...relaxed, allowSamePositionBackToBack: false }).errors.some(e => e.includes('back-to-back')));
});

test('infield, outfield and bench streak limits follow settings', () => {
  const players = roster(11);
  const assignments = repeated(players);
  for (const [setting, message] of [
    ['maxConsecutiveInfield', 'plays infield'],
    ['maxConsecutiveOutfield', 'plays outfield'],
    ['maxConsecutiveBench', 'sits']
  ] as const) {
    assert(validateAll(assignments, players, { ...relaxed, [setting]: 1 }).errors.some(e => e.includes(message)));
    assert(!validateAll(assignments, players, relaxed).errors.some(e => e.includes(message)));
  }
});

test('empty outfield, dugout and early infield switches work', () => {
  const players = roster(10);
  const assignments = repeated(players);
  assert(validateAll(assignments, players, { ...relaxed, requireDugout: true }).warnings.some(e => e.includes('No players')));
  assert(validateAll(assignments, players, { ...relaxed, requireEarlyInfieldByInning3: true }).errors.some(e => e.includes('no infield')));
  delete assignments.byInning[1].RF;
  assignments.byInning[1].dugout.push('9');
  assert.equal(validateAll(assignments, players, relaxed).errors.length, 0);
  assert(validateAll(assignments, players, { ...relaxed, allowEmptyOutfield: false }).errors.some(e => e.includes('RF is unassigned')));
});

test('absent players are excluded and checking them in restores rules', () => {
  const players = roster(11);
  const assignments = repeated(players);
  const settings = { ...DEFAULT_SETTINGS, customRules: ["December doesn't play catcher"] };
  players[0].active = false;
  const result = validateAll(assignments, players, settings);
  assert(![...result.errors, ...result.warnings].some(e => e.includes('December')));
  players[0].active = true;
  assert(validateAll(assignments, players, settings).errors.some(e => e.includes('December cannot play catcher')));
});

test('custom restrictions support straight and curly apostrophes and additional pitchers', () => {
  const players = roster(12);
  for (const rule of ["December doesn't play catcher", 'December doesn\u2019t play catcher', 'December cannot play pitcher']) {
    const settings: Settings = { ...relaxed, customRules: [rule], additionalPositions: [{ id: 'P2', group: 'INFIELD' }, { id: 'OF5', group: 'OUTFIELD' }] };
    for (let run = 0; run < 5; run++) {
      const assignments = autoGenerateDefense(players, 3, settings);
      assert.equal(validateAll(assignments, players, settings).errors.length, 0);
      for (const inning of Object.values(assignments.byInning)) {
        if (rule.includes('pitcher')) {
          assert.notEqual(inning.P, '0');
          assert.notEqual(inning.P2, '0');
        } else assert.notEqual(inning.C, '0');
        assert(inning.P2 && inning.OF5);
      }
    }
  }
});

test('generation allows repeats when disabled, including games longer than position count', () => {
  const players = roster(10);
  const assignments = autoGenerateDefense(players, 11, relaxed);
  assert.equal(validateAll(assignments, players, relaxed).errors.length, 0);
  for (const inning of Object.values(assignments.byInning)) {
    assert.equal(getAllPositions().filter(pos => inning[pos]).length, 10);
  }
});

test('default generation follows rules across repeated runs and roster sizes', () => {
  for (const count of [10, 11, 12]) {
    const players = roster(count);
    for (let run = 0; run < 10; run++) {
      const assignments = autoGenerateDefense(players, 5, DEFAULT_SETTINGS);
      assert.deepEqual(validateAll(assignments, players, DEFAULT_SETTINGS).errors, []);
    }
  }
});

test('Auto Fix enforces custom rules, preserves hidden innings and leaves valid rotations alone', () => {
  const players = roster(11);
  const assignments = repeated(players);
  assignments.byInning[4] = { C: '0', dugout: [] };
  const settings = { ...relaxed, customRules: ["December doesn't play catcher", 'Max bench 1', 'No same position twice'] };
  const fixed = autoFixViolations(assignments, players, settings);
  assert.deepEqual(validateAll(fixed, players, settings).errors, []);
  assert.deepEqual(fixed.byInning[4], assignments.byInning[4]);
  assert.equal(autoFixViolations(fixed, players, settings), fixed);
});

test('impossible rule combinations remain flagged', () => {
  const players = roster(6);
  const settings = { ...DEFAULT_SETTINGS, maxConsecutiveInfield: 1 };
  const assignments = autoGenerateDefense(players, 3, settings);
  assert(validateAll(assignments, players, settings).errors.length > 0);
  assert(validateAll(autoFixViolations(assignments, players, settings), players, settings).errors.length > 0);
});
