import { useState, useEffect, useCallback } from "react";
import { Player, DefenseAssignments, Settings, SavedGame, TeamBranding, GameLog } from "../types";
import { DEFAULT_SETTINGS, PLAYER_COLORS } from "../constants";
import { autoGenerateDefense } from "../utils";

export function useAppState(teamId?: string) {
  const [players, setPlayers] = useState<Player[]>([]);
  const [battingOrder, setBattingOrder] = useState<string[]>([]);
  const [assignments, setAssignments] = useState<DefenseAssignments>({
    innings: DEFAULT_SETTINGS.inningsCount,
    byInning: {}
  });
  const [settings, setSettings] = useState<Settings>(DEFAULT_SETTINGS);
  const [branding, setBranding] = useState<TeamBranding>({ teamName: "My Team" });
  const [savedGames, setSavedGames] = useState<SavedGame[]>([]);
  const [activeGameId, setActiveGameId] = useState<string | null>(null);
  const [masterRoster, setMasterRoster] = useState<Player[]>([]);
  const [gameLog, setGameLog] = useState<GameLog | undefined>(undefined);
  const [loading, setLoading] = useState(!!teamId);
  const [hasHydratedTeam, setHasHydratedTeam] = useState(!teamId);

  useEffect(() => {
    setHasHydratedTeam(!teamId);
  }, [teamId]);

  // Fetch team data
  useEffect(() => {
    if (!teamId) return;

    const fetchTeam = async () => {
      setLoading(true);
      try {
        const res = await fetch("/api/teams");
        const teams = await res.json();
        const team = teams.find((t: any) => t.id === teamId);
        if (team) {
          setBranding(team.branding);
          setSettings(team.settings);
          setMasterRoster(team.roster);
          // For a new game session, we start with master roster
          setPlayers(team.roster);
          setBattingOrder(team.roster.map((p: any) => p.id));
        }

        const gamesRes = await fetch(`/api/teams/${teamId}/games`);
        const games = await gamesRes.json();
        setSavedGames(games);

        // Load saved working draft (lineup + defense) so game-day setup isn't lost.
        const draftRes = await fetch(`/api/teams/${teamId}/draft`);
        if (draftRes.ok) {
          const draft = await draftRes.json();
          if (draft) {
            if (Array.isArray(draft.players) && draft.players.length > 0) {
              setPlayers(draft.players);
            }
            if (Array.isArray(draft.battingOrder) && draft.battingOrder.length > 0) {
              setBattingOrder(draft.battingOrder);
            }
            if (draft.assignments) {
              setAssignments(draft.assignments);
            }
            if (draft.log) {
              setGameLog(draft.log);
            }
          }
        }
      } catch (e) {
        console.error("Failed to load team", e);
      } finally {
        setLoading(false);
        setHasHydratedTeam(true);
      }
    };

    fetchTeam();
  }, [teamId]);

  // Save team settings/roster when they change
  const saveTeamState = useCallback(async () => {
    if (!teamId) return;
    try {
      await fetch(`/api/teams/${teamId}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: branding.teamName,
          branding,
          settings,
          roster: masterRoster
        })
      });
    } catch (e) {
      console.error("Failed to save team state", e);
    }
  }, [teamId, branding, settings, masterRoster]);

  // Auto-save team state on changes (debounced or just on specific actions)
  // For now, let's call it manually or on specific updates

  const saveAsMasterRoster = useCallback(() => {
    setMasterRoster(players);
    // Trigger save
  }, [players]);

  useEffect(() => {
    if (!teamId || !hasHydratedTeam) return;
    saveTeamState();
  }, [teamId, hasHydratedTeam, masterRoster, settings, branding, saveTeamState]);

  const saveDraftState = useCallback(async () => {
    if (!teamId) return;
    try {
      await fetch(`/api/teams/${teamId}/draft`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          players,
          battingOrder,
          assignments,
          settings,
          branding,
          log: gameLog
        })
      });
    } catch (e) {
      console.error("Failed to save working draft", e);
    }
  }, [teamId, players, battingOrder, assignments, settings, branding, gameLog]);

  useEffect(() => {
    if (!teamId || !hasHydratedTeam) return;
    const timer = setTimeout(() => {
      saveDraftState();
    }, 600);
    return () => clearTimeout(timer);
  }, [teamId, hasHydratedTeam, players, battingOrder, assignments, settings, branding, gameLog, saveDraftState]);

  const loadMasterRoster = useCallback(() => {
    if (masterRoster.length > 0) {
      setPlayers(masterRoster);
      setBattingOrder(masterRoster.map(p => p.id));
    }
  }, [masterRoster]);

  const startNewGame = useCallback((keepRoster: boolean = true) => {
    if (!keepRoster) {
      setPlayers([]);
      setBattingOrder([]);
    }
    setAssignments({
      innings: settings.inningsCount,
      byInning: Object.fromEntries(Array.from({length: settings.inningsCount}, (_, i) => [i+1, {dugout: []}]))
    });
    setGameLog(undefined);
    setActiveGameId(null);
  }, [settings.inningsCount]);

  const addPlayer = useCallback((name: string) => {
    const newPlayer: Player = {
      id: crypto.randomUUID(),
      name,
      color: PLAYER_COLORS[players.length % PLAYER_COLORS.length],
      active: true
    };
    setPlayers(prev => [...prev, newPlayer]);
    setMasterRoster(prev => [...prev, newPlayer]);
    setBattingOrder(prev => [...prev, newPlayer.id]);
  }, [players.length]);

  const bulkAddPlayers = useCallback((names: string) => {
    const newNames = names.split("\n").map(n => n.trim()).filter(n => n.length > 0);
    const newPlayers: Player[] = newNames.map((name, i) => ({
      id: crypto.randomUUID(),
      name,
      color: PLAYER_COLORS[(players.length + i) % PLAYER_COLORS.length],
      active: true
    }));
    setPlayers(prev => [...prev, ...newPlayers]);
    setMasterRoster(prev => [...prev, ...newPlayers]);
    setBattingOrder(prev => [...prev, ...newPlayers.map(p => p.id)]);
  }, [players.length]);

  const updatePlayer = useCallback((id: string, updates: Partial<Player>) => {
    setPlayers(prev => prev.map(p => p.id === id ? { ...p, ...updates } : p));
    const { active, ...rosterUpdates } = updates;
    if (Object.keys(rosterUpdates).length > 0) {
      setMasterRoster(prev => prev.map(p => p.id === id ? { ...p, ...rosterUpdates } : p));
    }
    
    if (updates.active !== undefined) {
      setGameLog(prev => {
        if (!prev) return prev;
        const next = { ...prev };
        next.playerStats = { ...next.playerStats };
        if (next.playerStats[id]) {
          next.playerStats[id] = { ...next.playerStats[id], played: updates.active };
        } else {
          next.playerStats[id] = { ab: 0, played: updates.active };
        }
        return next;
      });
    }
  }, []);

  const deletePlayer = useCallback((id: string) => {
    setPlayers(prev => prev.filter(p => p.id !== id));
    setMasterRoster(prev => prev.filter(p => p.id !== id));
    setBattingOrder(prev => prev.filter(pid => pid !== id));
    setAssignments(prev => {
      const next = { ...prev };
      for (let i = 1; i <= next.innings; i++) {
        const inning = { ...next.byInning[i] };
        Object.keys(inning).forEach(pos => {
          if (inning[pos] === id) delete inning[pos];
        });
        inning.dugout = inning.dugout.filter(pid => pid !== id);
        next.byInning[i] = inning;
      }
      return next;
    });
  }, []);

  const saveGame = useCallback(async (meta: SavedGame["meta"]) => {
    if (!teamId) return;
    const newGameData = {
      meta,
      players,
      batting_order: battingOrder,
      assignments,
      log: gameLog
    };

    try {
      const res = await fetch(`/api/teams/${teamId}/games`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(newGameData)
      });
      if (res.ok) {
        const { id } = await res.json();
        const newGame: SavedGame = {
          id,
          meta,
          players,
          battingOrder,
          assignments,
          settings,
          branding,
          log: gameLog
        };
        setSavedGames(prev => [...prev, newGame]);
        setGameLog(undefined);
      }
    } catch (e) {
      console.error("Failed to save game", e);
    }
  }, [teamId, players, battingOrder, assignments, settings, branding, gameLog]);

  const loadGame = useCallback((game: SavedGame) => {
    setPlayers(game.players);
    setBattingOrder(game.battingOrder);
    setAssignments(game.assignments);
    setSettings(game.settings);
    setBranding(game.branding);
    setGameLog(game.log);
    setActiveGameId(game.id);
  }, []);

  const generateDefense = useCallback(() => {
    const activePlayers = players.filter(p => p.active !== false);
    const newAssignments = autoGenerateDefense(activePlayers, settings.inningsCount, settings, savedGames);
    setAssignments(newAssignments);
  }, [players, settings, savedGames]);

  const updateBranding = useCallback((updates: Partial<TeamBranding>) => {
    setBranding(prev => ({ ...prev, ...updates }));
  }, []);

  return {
    players, setPlayers,
    battingOrder, setBattingOrder,
    assignments, setAssignments,
    settings, setSettings,
    branding, setBranding: updateBranding,
    savedGames, setSavedGames,
    gameLog, setGameLog,
    loading,
    addPlayer, bulkAddPlayers, updatePlayer, deletePlayer,
    saveGame, loadGame, generateDefense,
    saveAsMasterRoster, loadMasterRoster, startNewGame
  };
}
